"""Adding submission relationships

Revision ID: 412ec37aa1a9
Revises: 3c3ed2fca236
Create Date: 2015-03-18 17:41:41.238927

"""

# revision identifiers, used by Alembic.
revision = '412ec37aa1a9'
down_revision = '3c3ed2fca236'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
